## El Método de K-Means

In [17]:
import numpy as np

In [18]:
data = np.random.random(90).reshape(30,3)

In [22]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.63149921, 0.87181336, 0.69323898],
       [0.02939157, 0.49733841, 0.0100447 ]])

In [23]:
from scipy.cluster.vq import vq

La función vq(data, clusters) arroja dos arreglos.
* 1. Cada dato de "data" a cuál cluster pertenece
* 2. La distancia de cada dato de "data" hasta su cluster

In [25]:
vq(data, clust_centers)

(array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
        1, 0, 0, 0, 0, 1, 0, 1]),
 array([0.70106476, 0.91010175, 0.15948481, 0.44525349, 0.90699844,
        0.48314557, 0.58228561, 0.56372068, 0.77355846, 0.61051505,
        0.71348297, 0.17841916, 0.92196782, 0.26955943, 0.        ,
        0.        , 0.50023439, 0.5518341 , 0.44047345, 0.30969668,
        0.21994693, 0.87029657, 0.59578531, 0.90632357, 0.55352955,
        0.2313241 , 0.38099945, 0.41908605, 0.53013788, 0.63243065]))

In [26]:
from scipy.cluster.vq import kmeans

La función kmeans(data, clusters) arroja los centros de cada k cluster y la suma total de distancias cuadradas (es un porcentaje de error)

La función kmeans(data, k) arroja los centros de los k clusters y la distancia total (mientras menor sea, mejor)

In [28]:
kmeans(data, clust_centers)

(array([[0.67120522, 0.55206604, 0.64686962],
        [0.40249532, 0.44606677, 0.21016083]]), 0.4177179942048118)

In [29]:
kmeans(data, 2)

(array([[0.57958189, 0.28185604, 0.49902657],
        [0.5847153 , 0.86904832, 0.50471019]]), 0.39316581929983824)